version: '3.7'

services:
  database:
    image: postgres:12.0-alpine
    volumes:
      - development_database:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=starter
    ports:
    - "5432:5432"
volumes:
  development_database:
